spring:
  r2dbc:
    password: root
    username: root
    url: r2dbc:postgresql://nas.8910.xyz:4000/blog
#    password: root
#    username: postgres
#    url: r2dbc:postgresql://localhost:5432/blog
  redis:
    host: nas.8910.xyz
    port: 6379
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters