spring:
  r2dbc:
    pool:
      enabled: true
      max-size: 10
      initial-size: 4
    username: root
    password: root
    url: r2dbc:mysql://localhost:3306/blog
  redis:
    host: localhost
    port: 6379
    password:
