#logging:
#  level:
#    io.r2dbc.postgresql.QUERY: DEBUG # for queries
#    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
spring:
  r2dbc:
    username: root
    password: root
    url: r2dbc:mysql://localhost:3306/blog
  redis:
    host: localhost
    port: 6379
    password:
