spring:
  r2dbc:
    pool:
      enabled: true
      max-size: 10
      initial-size: 4
    username: root
    password: root
    url: r2dbc:postgresql://localhost:5432/explore
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        enabled: true
        max-active: 10
        min-idle: 4
