spring:
  profiles:
    active: dev
    group:
      dev: dev,dev-local
      prod: prod,prod-local
  data:
    redis:
      repositories:
        enabled: false
graphql:
  schema:
    location: classpath*:/graphql/**/*.graphql*