logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
spring:
  r2dbc:
    username: root
    password: root
    url: r2dbc:postgresql://localhost:3306/explore
    pool:
      initial-size: 1
      max-size: 3
  redis:
    host: localhost
    port: 6379
    password:
    client-type: lettuce

