name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'

      - name: build
        run: ./gradlew build

      - name: test
        run: ./gradlew test

      - name: jar
        run: ./gradlew bootJar

      - name: archive jar
        uses: actions/upload-artifact@v2
        with:
          name: explore-server-libs
          path: server/build/libs

      - name: Set up QEMU
        if: ${{ github.event_name == 'push' }}
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: ${{ github.event_name == 'push' }}
        uses: docker/setup-buildx-action@v1

      - name: login to docker hub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        # 配置登录信息，secrets 变量在 github settings -> secrets 中设置
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build dockerfile (with push)
        # 构建镜像，用buildx可以同时构建X86和ARM架构的镜像，然后推送到hub.docker.com
        run: |
          fullCommit="${{ github.event.commits[0].id }}" && \
          docker buildx build \
          --platform=linux/amd64,linux/arm/v7,linux/arm64 \
          --output "type=image,push=true" \
          --file ./Dockerfile . \
          --tag rhysxia/explore-server:"${fullCommit: 0: 7}"

