name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'

      - name: build
        run: ./gradlew build

      - name: test
        run: ./gradlew test

      - name: jar
        run: ./gradlew bootJar

      - name: archive jar
        uses: actions/upload-artifact@v2
        with:
          name: server.jar
          path: server/build/libs